// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI는 libsql:// 미지원 — Turso 마이그레이션은 scripts/turso-migrate.mjs 사용
    url: process.env.DATABASE_URL ?? "file:./dev.db",
  },
});
