// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI는 libsql:// 미지원. Turso는 scripts/turso-migrate.mjs + lib/db/prisma.ts
    url: "file:./dev.db",
  },
});
